import LargeTimerCard from "../components/largeTimerCard";
import SmallTimerCard from "../components/smallTimerCard";
import {
  AppleLogo,
  CrunchyrollLogo,
  FandangoLogo,
  GooglePlayMoviesLogo,
  HBOLogo,
  HuluLogo,
  NetflixLogo,
} from "./svgs/svgLogos";

import ADTheBeginning from "./assets/ADTheBeginning.jpg";
import ApothecaryDiaries from "./assets/ApothecaryDiaries.jpg";
import AllCreaturesSeason3Episode3 from "./assets/AllCreaturesSeason3Episode3.jpg";
import Attack from "./assets/Attack.jpg";
import AttackLogo from "./assets/AttackLogo.jpg";
import ChainsawManMovie from "./assets/ChainsawManMovie.jpg";
import DanDaDan from "./assets/DanDaDan.jpg";
import DandadanLogo from "./assets/DandadanLogo.jpg";
import FoundationAvatar from "./assets/FoundationAvatar.jpg";
import FoundationSeason3 from "./assets/FoundationSeason3.jpg";
import FoundationSeason3Episode2 from "./assets/FoundationSeason3Episode2.jpg";
import FoundationSeason3Episode3 from "./assets/FoundationSeason3Episode3.jpg";
import FrierenFrierensParty from "./assets/FrierenFrierensParty.jpg";
import FrierenLogo from "./assets/FrierenLogo.jpg";
import JamesLogo from "./assets/JamesLogo.jpg";
import MaomaoSmall from "./assets/MaomaoSmall.jpg";
import Masterchef from "./assets/Masterchef.jpg";
import MasterchefLogo from "./assets/MasterchefLogo.jpg";
import MyHeroFinalSeason from "./assets/MyHeroFinalSeason.jpg";
import MyHeroLogo from "./assets/MyHeroLogo.jpg";
import NobodyWants from "./assets/NobodyWants.jpg";
import NobodyWantsLogo from "./assets/NobodyWantsLogo.jpg";
import Nyaight from "./assets/Nyaight.jpg";
import NyaightLogo from "./assets/NyaightLogo.jpg";
import OnlyMurdersintheBuilding from "./assets/OnlyMurdersintheBuilding.jpg";
import OnlyMurdersLogo from "./assets/OnlyMurdersLogo.jpg";
import PeacemakerLogo from "./assets/PeacemakerLogo.jpg";
import PeacemakerSeason2 from "./assets/PeacemakerSeason2.jpg";
import Pochita from "./assets/Pochita.jpg";
import SlowHorsesBig from "./assets/SlowHorses.jpg";
import SlowHorsesLogo from "./assets/SlowHorsesLogo.jpg";
import SoloLeveling from "./assets/SoloLeveling.jpg";
import SoloLogo from "./assets/SoloLogo.jpg";
import Stone from "./assets/Stone.jpg";
import StoneLogo from "./assets/StoneLogo.jpg";
import StrangerLogo from "./assets/StrangerLogo.jpg";
import StrangerThings from "./assets/StrangerThings.jpg";
import Superman from "./assets/Superman.jpg";
import SupermanLogo from "./assets/SupermanLogo.jpg";
import TheBearLogo from "./assets/TheBearLogo.jpg";
import TheBearSeason4Episode3 from "./assets/TheBearSeason4Episode3.jpg";
import VinlandLogo from "./assets/VinlandLogo.jpg";
import VinlandSaga from "./assets/VinlandSaga.jpg";

export interface AvailableNowProps {
  avatar: string;
  title: string;
  subheader: string;
  season?: number;
  episode?: number;
  cardMedia: string;
  cardMediaAlt: string;
  releaseDateTime: string;
  synopsis?: string;
  watchUrl: string;
  estimate?: boolean;
  estimateDate?: string;
  isMovie?: boolean;
  addContrastToTimer?: boolean;
  objectPosition?: string;
  finale?: boolean;
  SiteLogo:
    | typeof AppleLogo
    | typeof CrunchyrollLogo
    | typeof FandangoLogo
    | typeof HBOLogo
    | typeof HuluLogo
    | typeof NetflixLogo;
}

export interface UpNextProps extends AvailableNowProps {
  TimerCard: typeof LargeTimerCard | typeof SmallTimerCard;
}

export const availableNow: AvailableNowProps[] = [
  {
    avatar: SupermanLogo.src,
    title: "Superman",
    subheader: "",
    cardMedia: Superman.src,
    cardMediaAlt: "Superman",
    releaseDateTime: "July 11, 2025 16:00:00",
    synopsis:
      "Superman must reconcile his alien Kryptonian heritage with his human upbringing as reporter Clark Kent. As the embodiment of truth, justice and the human way he soon finds himself in a world that views these as old-fashioned.",
    isMovie: true,
    watchUrl: "https://www.fandango.com/superman-2025-230934/movie-overview",
    objectPosition: "50% 50%",
    SiteLogo: FandangoLogo,
  },
  {
    avatar: JamesLogo.src,
    title: "All Creatures Great And Small",
    subheader: "Surviving Siegfried",
    season: 3,
    episode: 3,
    cardMedia: AllCreaturesSeason3Episode3.src,
    cardMediaAlt: "Siegfried and a racehorse",
    releaseDateTime: "January 22, 2023 21:00:00",
    synopsis:
      "Siegfried receives some news and channels his feelings into saving a young racehorse. James struggles to get farmers to agree to his newly adopted TB testing scheme.",
    watchUrl:
      "https://play.google.com/store/tv/show?id=gbQjVgRNYkg.P&cdid=tvseason-mjGu8FIpiU4.P&hl=en_US",
    objectPosition: "50% 47%",
    SiteLogo: GooglePlayMoviesLogo,
  },
  {
    avatar: TheBearLogo.src,
    title: "The Bear",
    subheader: "Scallop",
    season: 4,
    episode: 3,
    cardMedia: TheBearSeason4Episode3.src,
    cardMediaAlt: "The Bear Season 4 Episode 3",
    releaseDateTime: "June 25, 2025 21:00:00",
    synopsis: "Opportunity.",
    watchUrl:
      "https://www.hulu.com/series/05eb6a8e-90ed-4947-8c0b-e6536cbddd5f",
    objectPosition: "30% 50%",
    SiteLogo: HuluLogo,
  },
  {
    avatar: AttackLogo.src,
    title: "Attack on Titan",
    subheader: "Historia",
    season: 2,
    episode: 5,
    cardMedia: Attack.src,
    cardMediaAlt: "Attack on Titan",
    releaseDateTime: "April 29 2017 03:00:00 GMT-0700",
    synopsis:
      "Utgard Castle comes crumbling down as Ymir desperately battles the Titans. Now, Christa must fulfill the promise they made long ago during winter training.",
    watchUrl: "https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan",
    objectPosition: "15% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: MasterchefLogo.src,
    title: "Masterchef",
    subheader: "Mister-y & Mrs. Box",
    season: 15,
    episode: 5,
    cardMedia: Masterchef.src,
    cardMediaAlt: "Masterchef",
    releaseDateTime: "June 18 2025 03:00:00 GMT-0700",
    synopsis:
      "In the first Mystery Box challenge of the season, the Top 11 duos must combine two boxes of ingredients to make a harmonious dish.",
    watchUrl:
      "https://www.hulu.com/series/45d67197-5346-4adb-9d90-6ed2d7b7bd85",
    objectPosition: "50% 30%",
    SiteLogo: HuluLogo,
  },
  {
    avatar: SoloLogo.src,
    title: "Solo Leveling",
    subheader: "I need to stop faking it",
    season: 2,
    episode: 4,
    cardMedia: SoloLeveling.src,
    cardMediaAlt: "Solo Leveling",
    releaseDateTime: "January 25 2025 03:00:00 GMT-0700",
    synopsis:
      "Jinwoo realizes that he'll need to become even stronger in order to clear the Demon's Castle and decides to have his hunter rank reassessed.",
    watchUrl: "https://www.crunchyroll.com/series/GDKHZEJ0K/solo-leveling",
    objectPosition: "10% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: StoneLogo.src,
    title: "Dr. Stone",
    subheader: "Stone Wars Beginning",
    season: 2,
    episode: 1,
    cardMedia: Stone.src,
    cardMediaAlt: "Dr. Stone",
    releaseDateTime: "May 16 2021 03:00:00 GMT-0700",
    synopsis: `Senku continues in trying to advance the Stone World, this time he makes "space food", it is in actuality cup noodles. After Senku finishes his project, Gen has an epiphany and devises a plan to take down Tsukasa's army without violence.`,
    watchUrl: "https://www.crunchyroll.com/series/GYEXQKJG6/dr-stone",
    objectPosition: "50% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "I've Got This Funny Feeling",
    season: 1,
    episode: 8,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "November 21 2024 03:00:00 GMT-0700",
    synopsis: `The battle against Acrobatic Silky is over, Aira's romantic feelings stem from how Okarun saved her. As Momo, Okarun, and Aira's feelings intertwine, Serpoians make another appearance, and the three of them are trapped in void space.`,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: VinlandLogo.src,
    title: "Vinland Saga",
    subheader: "For the Love That Was Lost",
    season: 2,
    episode: 12,
    cardMedia: VinlandSaga.src,
    cardMediaAlt: "Vinland Saga",
    releaseDateTime: "March 21 2023 03:00:00 GMT-0700",
    synopsis:
      "Olmar recieves some upsetting news, causing him to reach his breaking point. Meawhile, tensions arise as Canute sets his sights on Ketil's farm.",
    watchUrl: "https://www.crunchyroll.com/series/GEXH3WKK0/vinland-saga",
    objectPosition: "50% 34%",
    SiteLogo: CrunchyrollLogo,
  },
];

export const upNext: UpNextProps[] = [
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 3,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "July 20 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 4,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "July 24 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: LargeTimerCard,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 3,
    cardMedia: FoundationSeason3Episode3.src,
    cardMediaAlt: "Foundation Season 3 Episode 3",
    releaseDateTime: "July 25 2025 03:00:00 GMT-0700",
    synopsis:
      " An unexpected alliance is formed. Pritcher, Bayta, and Toran come face-to-face with the Mule. Demerzel seeks spiritual guidance.",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: LargeTimerCard,
    SiteLogo: AppleLogo,
  },

  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 4,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "July 27 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 5,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "July 31 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 4,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 4",
    releaseDateTime: "August 1 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 5,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 03 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 6,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "August 07 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 5,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 5",
    releaseDateTime: "August 8 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 6,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 10 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 7,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "August 14 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 6,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 6",
    releaseDateTime: "August 15 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 7,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 17 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 8,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "August 21 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "August 21 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: LargeTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 7,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 7",
    releaseDateTime: "August 22 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },

  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 8,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 24 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 1,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "August 26, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    estimate: true,
    estimateDate: "[Best Guess] August 2025",
    objectPosition: "100% 20%",
    TimerCard: LargeTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 9,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "August 28 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 2,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "August 28 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 8,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 8",
    releaseDateTime: "August 29 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },

  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 9,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 31 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 10,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "September 04 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 3,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 04 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 9,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 9",
    releaseDateTime: "September 05 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 10,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "September 07 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 11,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "September 11 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 4,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 11 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 10,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 10",
    releaseDateTime: "September 12 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 40%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    finale: true,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 11,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "September 14 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dan Da Dan",
    subheader: "",
    season: 2,
    episode: 12,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "September 18 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    finale: true,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 5,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 18 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 12,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "September 21 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    finale: true,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 1,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "September 24, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: LargeTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 2,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "September 24, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 6,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 25 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 3,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 01, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 7,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "October 02 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 1,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "October 05, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 4,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 08, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 8,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "October 09 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
    finale: true,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 5,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 15, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 6,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 22, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
    finale: true,
  },
  {
    avatar: NobodyWantsLogo.src,
    title: "Nobody Wants This",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: NobodyWants.src,
    cardMediaAlt: "Nobody Wants This",
    releaseDateTime: "October 23, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/81591296",
    objectPosition: "50% 50%",
    TimerCard: LargeTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: Pochita.src,
    title: "Chainsaw Man - The Movie: Reze Arc",
    subheader: "",
    cardMedia: ChainsawManMovie.src,
    cardMediaAlt: "Chainsaw Man - The Movie: Reze Arc",
    releaseDateTime: "October 29, 2025 16:00:00",
    synopsis:
      "Denji encounters a new romantic interest, Reze, who works at a coffee café.",
    isMovie: true,
    watchUrl:
      "https://www.fandango.com/chainsaw-man-the-movie-reze-arc-2025-241288/movie-overview",
    objectPosition: "50% 25%",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
    addContrastToTimer: true,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter One: The Crawl",
    season: 5,
    episode: 1,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: LargeTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Two: The Vanishing of",
    season: 5,
    episode: 2,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Three: The Turnbow Trap",
    season: 5,
    episode: 3,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Four: Sorcerer",
    season: 5,
    episode: 4,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Five: Shock Jock",
    season: 5,
    episode: 5,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Six: Escape from Camazotz",
    season: 5,
    episode: 6,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Seven: The Bridge",
    season: 5,
    episode: 7,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Eight: The Rightside Up",
    season: 5,
    episode: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 31, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
    finale: true,
  },
  {
    avatar: FrierenLogo.src,
    title: "Frieren: Beyond Journey's End",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: FrierenFrierensParty.src,
    cardMediaAlt: "Frieren's Party",
    releaseDateTime: "January 31, 2026 23:00:00",
    watchUrl:
      "https://www.crunchyroll.com/series/GG5H5XQX4/frieren-beyond-journeys-end",
    estimate: true,
    estimateDate: "January 2026",
    objectPosition: "50% 28%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
];
