import LargeTimerCard from "../components/largeTimerCard";
import SmallTimerCard from "../components/smallTimerCard";
import {
  AppleLogo,
  CrunchyrollLogo,
  FandangoLogo,
  GooglePlayMoviesLogo,
  HBOLogo,
  HuluLogo,
  IMDBLogo,
  NetflixLogo,
} from "./svgs/svgLogos";

import TwentyEightYears from "./assets/28Years.jpg";
import TwentyEightYearsLogo from "./assets/28YearsLogo.jpg";
import AllCreaturesS3E4 from "./assets/AllCreaturesS3E4.jpg";
import Attack from "./assets/Attack.jpg";
import AttackLogo from "./assets/AttackLogo.jpg";
import ChainsawManMovie from "./assets/ChainsawManMovie.jpg";
import Creature from "./assets/Creature.jpg";
import CreatureLogo from "./assets/CreatureLogo.jpg";
import DanDaDan from "./assets/DanDaDan.jpg";
import DandadanLogo from "./assets/DandadanLogo.jpg";
import Fantastic from "./assets/Fantastic.jpg";
import FantasticLogo from "./assets/FantasticLogo.jpg";
import FoundationAvatar from "./assets/FoundationAvatar.jpg";
import FoundationSeason3 from "./assets/FoundationSeason3.jpg";
import FoundationS3E5 from "./assets/FoundationS3E5.jpg";
import FrierenFrierensParty from "./assets/FrierenFrierensParty.jpg";
import FrierenLogo from "./assets/FrierenLogo.jpg";
import Fruits from "./assets/Fruits.jpg";
import Gurren from "./assets/Gurren.jpg";
import Highest2Lowest from "./assets/Highest2Lowest.jpg";
import Highest2LowestLogo from "./assets/Highest2LowestLogo.jpg";
import Invasion from "./assets/Invasion.jpg";
import InvasionLogo from "./assets/InvasionLogo.jpg";
import JamesLogo from "./assets/JamesLogo.jpg";
import JeffBuckley from "./assets/JeffBuckley.jpg";
import JeffBuckleyLogo from "./assets/JeffBuckleyLogo.jpg";
import Kaiju from "./assets/Kaiju.jpg";
import LostBus from "./assets/LostBus.jpg";
import LostBusLogo from "./assets/LostBusLogo.jpg";
import Masterchef from "./assets/Masterchef.jpg";
import MasterchefLogo from "./assets/MasterchefLogo.jpg";
import Mickey17 from "./assets/Mickey17.jpg";
import Mickey17Logo from "./assets/Mickey17Logo.jpg";
import MyHeroFinalSeason from "./assets/MyHeroFinalSeason.jpg";
import MyHeroLogo from "./assets/MyHeroLogo.jpg";
import Naruto from "./assets/Naruto.jpg";
import NobodyWants from "./assets/NobodyWants.jpg";
import NobodyWantsLogo from "./assets/NobodyWantsLogo.jpg";
import Nyaight from "./assets/Nyaight.jpg";
import NyaightLogo from "./assets/NyaightLogo.jpg";
import Odyssey from "./assets/Odyssey.jpg";
import OdysseyLogo from "./assets/OdysseyLogo.jpg";
import OneBattle from "./assets/OneBattle.jpg";
import OneBattleLogo from "./assets/OneBattleLogo.jpg";
import OnlyMurdersintheBuilding from "./assets/OnlyMurdersintheBuilding.jpg";
import OnlyMurdersLogo from "./assets/OnlyMurdersLogo.jpg";
import PeacemakerLogo from "./assets/PeacemakerLogo.jpg";
import PeacemakerSeason2 from "./assets/PeacemakerSeason2.jpg";
import Pochita from "./assets/Pochita.jpg";
import ResidentAlien from "./assets/ResidentAlien.jpg";
import ResidentAlienLogo from "./assets/ResidentAlienLogo.jpg";
import RunningMan from "./assets/RunningMan.jpg";
import RunningManLogo from "./assets/RunningManLogo.jpg";
import Sandman from "./assets/Sandman.jpg";
import SandmanLogo from "./assets/SandmanLogo.jpg";
import SlowHorsesBig from "./assets/SlowHorses.jpg";
import SlowHorsesLogo from "./assets/SlowHorsesLogo.jpg";
import SoloLeveling from "./assets/SoloLeveling.jpg";
import SoloLogo from "./assets/SoloLogo.jpg";
import SquidGame from "./assets/SquidGameCoffins.jpg";
import SquidLogo from "./assets/SquidLogo.jpg";
import Stone from "./assets/Stone.jpg";
import StoneLogo from "./assets/StoneLogo.jpg";
import StrangerLogo from "./assets/StrangerLogo.jpg";
import StrangerThings from "./assets/StrangerThings.jpg";
import Tar from "./assets/Tar.jpg";
import TarLogo from "./assets/TarLogo.jpg";
import TheBearLogo from "./assets/TheBearLogo.jpg";
import TheBearS4E5 from "./assets/TheBearS4E5.jpg";
import TheBrutalist from "./assets/TheBrutalist.jpg";
import TheBrutalistLogo from "./assets/TheBrutalistLogo.jpg";
import VinlandLogo from "./assets/VinlandLogo.jpg";
import VinlandSaga from "./assets/VinlandSaga.jpg";
import WhiteLotusLogo from "./assets/WhiteLotusLogo.jpg";
import WhiteLotusS2 from "./assets/WhiteLotusS2.jpg";
import ZoneOfInterest from "./assets/ZoneOfInterest.jpg";
import ZoneOfInterestLogo from "./assets/ZoneOfInterestLogo.jpg";

export interface AvailableNowProps {
  avatar: string;
  title: string;
  subheader: string;
  season?: number;
  episode?: number;
  episodesInSeason?: number;
  cardMedia: string;
  cardMediaAlt: string;
  releaseDateTime: string;
  synopsis?: string;
  watchUrl: string;
  estimate?: boolean;
  estimateDate?: string;
  isMovie?: boolean;
  addContrastToTimer?: boolean;
  objectPosition?: string;
  finale?: boolean;
  SiteLogo:
    | typeof AppleLogo
    | typeof CrunchyrollLogo
    | typeof FandangoLogo
    | typeof HBOLogo
    | typeof HuluLogo
    | typeof NetflixLogo;
}

export interface UpNextProps extends AvailableNowProps {
  TimerCard: typeof LargeTimerCard | typeof SmallTimerCard;
}

export const availableNow: AvailableNowProps[] = [
  {
    avatar: JamesLogo.src,
    title: "All Creatures Great And Small",
    subheader: "What a Balls Up!",
    season: 3,
    episode: 4,
    episodesInSeason: 7,
    cardMedia: AllCreaturesS3E4.src,
    cardMediaAlt: "All Creatures Great And Small Season 3 Episode 4",
    releaseDateTime: "January 29, 2023 21:00:00",
    synopsis:
      "James is finally succeeding with the farmers' uptake of the Ministry of Ag's TB testing scheme. Tristan is outgrowing running the small animal surgery and buys a car to help with errands at the practice, enabling him also taking a date out",
    watchUrl:
      "https://play.google.com/store/tv/show?id=gbQjVgRNYkg.P&cdid=tvseason-mjGu8FIpiU4.P&hl=en_US",
    objectPosition: "50% 50%",
    SiteLogo: GooglePlayMoviesLogo,
  },
  {
    avatar: TheBearLogo.src,
    title: "The Bear",
    subheader: "Replicants",
    season: 4,
    episode: 5,
    episodesInSeason: 10,
    cardMedia: TheBearS4E5.src,
    cardMediaAlt: "The Bear Season 4 Episode 5",
    releaseDateTime: "June 25, 2025 21:00:00",
    synopsis: "The team resets.",
    watchUrl:
      "https://www.hulu.com/series/05eb6a8e-90ed-4947-8c0b-e6536cbddd5f",
    objectPosition: "50% 50%",
    SiteLogo: HuluLogo,
  },
  {
    avatar: CreatureLogo.src,
    title: "Creature Commandos",
    subheader: "Chasing Squirrels",
    season: 1,
    episode: 4,
    episodesInSeason: 7,
    cardMedia: Creature.src,
    cardMediaAlt: "Creature Commandos",
    releaseDateTime: "December 19 2024 16:00:00 GMT-0700",
    synopsis: `The backstory of the Weasel is revealed.`,
    watchUrl:
      "https://play.hbomax.com/show/44f3a3fd-107e-49ac-bf74-c0383525b8ca",
    objectPosition: "50% 50%",
    SiteLogo: HBOLogo,
  },
  {
    avatar: Kaiju.src,
    title: "Kaiju No. 8",
    subheader: "Mission Recon",
    // season: 2,
    // episode: 1,
    cardMedia: Kaiju.src,
    cardMediaAlt: "Kaiju No. 8",
    releaseDateTime: "May 07 2025 03:00:00 GMT-0700",
    synopsis: `A group of Defense Force volunteers come together to try to defeat an army of ruthless Kaiju.`,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ7D/kaiju-no-8",
    objectPosition: "40% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: MasterchefLogo.src,
    title: "Masterchef",
    subheader: "Macaron Mayhem",
    season: 15,
    episode: 11,
    episodesInSeason: 13,
    cardMedia: Masterchef.src,
    cardMediaAlt: "Masterchef",
    releaseDateTime: "August 06 2025 03:00:00 GMT-0700",
    synopsis: `The duos must bake not just a dozen macarons, but a giant tower of perfectly formed delicacies.`,
    watchUrl:
      "https://www.hulu.com/series/45d67197-5346-4adb-9d90-6ed2d7b7bd85",
    objectPosition: "50% 30%",
    SiteLogo: HuluLogo,
  },
  {
    avatar: AttackLogo.src,
    title: "Attack on Titan",
    subheader: "Trust",
    season: 3,
    episode: 3,
    episodesInSeason: 22,
    cardMedia: Attack.src,
    cardMediaAlt: "Attack on Titan",
    releaseDateTime: "August 13 2018 03:00:00 GMT-0700",
    synopsis: `On the run and running out of time, the Scouts must entrust their lives to others if they plan on surviving.`,
    watchUrl: "https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan",
    objectPosition: "15% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: Gurren.src,
    title: "Gurren Lagann",
    subheader: "Well Met, Everyone",
    season: 1,
    episode: 14,
    episodesInSeason: 27,
    cardMedia: Gurren.src,
    cardMediaAlt: "Gurren Lagann",
    releaseDateTime: "September 22 2007 03:00:00 GMT-0700",
    synopsis: `One month has passed since the battle with Viral, and it's the sixth day of the battle for Teppelin. Guame and Cytomander with their troops confront Team Dai-Gurren.`,
    watchUrl: "https://www.crunchyroll.com/series/GEXH3WKK0/vinland-saga",
    objectPosition: "50% 20%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: StoneLogo.src,
    title: "Dr. Stone",
    subheader: "New World Map",
    season: 3,
    episode: 1,
    episodesInSeason: 22,
    cardMedia: Stone.src,
    cardMediaAlt: "Dr. Stone",
    releaseDateTime: "June 04 2023 03:00:00 GMT-0700",
    synopsis: `While continuing to use the hot air balloon to search for the oil, it's decided that Ishigami Village needs to take up agriculture to prevent future food shortages, as well as to produce preserved food for their upcoming sea voyage.`,
    watchUrl: "https://www.crunchyroll.com/series/GYEXQKJG6/dr-stone",
    objectPosition: "50% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: Fruits.src,
    title: "Fruits Basket",
    subheader: "Are You Really This Stupid?",
    season: 2,
    episode: 6,
    episodesInSeason: 25,
    cardMedia: Fruits.src,
    cardMediaAlt: "Fruits Basket",
    releaseDateTime: "May 12 2020 03:00:00 GMT-0700",
    synopsis: `Momiji convinces Tohru to join the Somas at their vacation house by the ocean for some fun in the sun.`,
    watchUrl: "https://www.crunchyroll.com/series/G6ZJMGEXY/fruits-basket",
    objectPosition: "50% 50%",
    SiteLogo: CrunchyrollLogo,
  },
];

export const backlog: AvailableNowProps[] = [
  {
    avatar: JeffBuckleyLogo.src,
    title: "It's Never Over, Jeff Buckley",
    subheader: "",
    synopsis:
      "Never-before-seen footage, exclusive voice messages, and accounts from Jeff Buckley's inner circle paint a captivating portrait of the gifted musician who died tragically in 1997, having only released one album.",
    cardMedia: JeffBuckley.src,
    cardMediaAlt: "It's Never Over, Jeff Buckley",
    releaseDateTime: "August 08 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.fandango.com/its-never-over-jeff-buckley-2025-241047/movie-overview",
    objectPosition: "65% 40%",
    SiteLogo: FandangoLogo,
    isMovie: true,
  },
  {
    avatar: FantasticLogo.src,
    title: "The Fantastic Four: First Steps",
    subheader: "",
    cardMedia: Fantastic.src,
    cardMediaAlt: "The Fantastic Four: First Steps",
    releaseDateTime: "July 25 2025 16:00:00 GMT-0700",
    synopsis:
      "Forced to balance their roles as heroes with the strength of their family bond, the Fantastic Four must defend Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    watchUrl:
      "https://www.fandango.com/the-fantastic-four-first-steps-2025-236967/movie-overview",
    objectPosition: "47% 15%",
    SiteLogo: FandangoLogo,
  },
  {
    avatar: ResidentAlienLogo.src,
    title: "Resident Alien",
    subheader: "Prisoners",
    season: 4,
    episode: 1,
    cardMedia: ResidentAlien.src,
    cardMediaAlt: "Resident Alien",
    releaseDateTime: "June 06 2025 16:00:00 GMT-0700",
    synopsis:
      "Harry must escape an outer space prison to stop a dangerous threat in town.",
    watchUrl: "https://www.imdb.com/title/tt8690918/?ref_=ttep_ov_bk",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
  },
  {
    avatar: SquidLogo.src,
    title: "Squid Game",
    subheader: "Keys and Knives",
    season: 3,
    episode: 1,
    cardMedia: SquidGame.src,
    cardMediaAlt: "Squid Game",
    releaseDateTime: "July 27 2025 16:00:00 GMT-0700",
    synopsis:
      "No-eul infiltrates a dangerous operation with a risky plan. A new game is announced: hide-and-seek, where one group holds a key and the other a knife.",
    watchUrl: "https://www.netflix.com/us/title/81040344",
    objectPosition: "50% 50%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: SandmanLogo.src,
    title: "The Sandman",
    subheader: "Season of Mists",
    season: 2,
    episode: 1,
    cardMedia: Sandman.src,
    cardMediaAlt: "The Sandman",
    releaseDateTime: "July 03 2025 16:00:00 GMT-0700",
    synopsis:
      "When a gathering of the Endless exposes deep-seated grievances, Morpheus embarks on a mission to Hell to free the soul of a condemned mortal.",
    watchUrl: "https://www.netflix.com/us/title/81150303",
    objectPosition: "50% 50%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: Naruto.src,
    title: "Naruto",
    subheader: "Identify Yourself: Powerful New Rivals",
    season: 1,
    episode: 21,
    cardMedia: Naruto.src,
    cardMediaAlt: "Naruto",
    releaseDateTime: "February 27 2003 16:00:00 GMT-0700",
    synopsis:
      "After the three ninjas take their leave, Sasuke realizes he has a powerful rival out there. The next day, Kakashi announces that he has recommended all of them for the Chuunin Exams. While Naruto and Sasuke are pleased, Sakura is afraid of letting everyone down. Also, someone decides they aren't ready and decides to test their abilities.",
    watchUrl: "https://www.crunchyroll.com/series/GY9PJ5KWR/naruto",
    objectPosition: "50% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: WhiteLotusLogo.src,
    title: "White Lotus",
    subheader: "Ciao",
    season: 2,
    episode: 1,
    cardMedia: WhiteLotusS2.src,
    cardMediaAlt: "White Lotus",
    releaseDateTime: "October 30 2022 16:00:00 GMT-0700",
    synopsis:
      "Two couples navigate awkwardness, an Italian American family deals with a conspicuous absence, and Tanya arrives with her new assistant.",
    watchUrl:
      "https://play.hbomax.com/show/14f9834d-bc23-41a8-ab61-5c8abdbea505",
    objectPosition: "50% 50%",
    SiteLogo: HBOLogo,
  },
  {
    avatar: ZoneOfInterestLogo.src,
    title: "The Zone of Interest",
    subheader: "",
    cardMedia: ZoneOfInterest.src,
    cardMediaAlt: "The Zone of Interest",
    releaseDateTime: "December 15 2023 16:00:00 GMT-0700",
    synopsis:
      "Auschwitz commandant Rudolf Höss and his wife Hedwig strive to build a dream life for their family in a house and garden beside the camp.",
    watchUrl: "https://www.imdb.com/title/tt7160372/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: TheBrutalistLogo.src,
    title: "The Brutalist",
    subheader: "",
    cardMedia: TheBrutalist.src,
    cardMediaAlt: "The Brutalist",
    releaseDateTime: "January 2024 16:00:00 GMT-0700",
    synopsis:
      "A visionary architect flees post-war Europe in 1947 for a brighter future in the United States and finds his life forever changed by a wealthy client.",
    watchUrl: "https://www.imdb.com/title/tt8999762/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: TarLogo.src,
    title: "Tár",
    subheader: "",
    cardMedia: Tar.src,
    cardMediaAlt: "Tár",
    releaseDateTime: "October 07 2022 16:00:00 GMT-0700",
    synopsis:
      "Set in the international world of Western classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors and the very first female director of a major German orchestra.",
    watchUrl: "https://www.imdb.com/title/tt14444726/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: TwentyEightYearsLogo.src,
    title: "28 Years Later",
    subheader: "",
    cardMedia: TwentyEightYears.src,
    cardMediaAlt: "28 Years Later",
    releaseDateTime: "June 20 2025 16:00:00 GMT-0700",
    synopsis:
      "A group of survivors of the rage virus live on a small island. When one of the group leaves the island on a mission into the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors.",
    watchUrl: "https://www.imdb.com/title/tt10548174/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: Mickey17Logo.src,
    title: "Mickey 17",
    subheader: "",
    cardMedia: Mickey17.src,
    cardMediaAlt: "Mickey 17",
    releaseDateTime: "March 07 2025 16:00:00 GMT-0700",
    synopsis: `During a human expedition to colonize space, Mickey 17, a so-called "expendable" employee, is sent to explore an ice planet.`,
    watchUrl: "https://www.imdb.com/title/tt12299608/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
];

export const upNext: UpNextProps[] = [
  {
    avatar: DandadanLogo.src,
    title: "Dandadan",
    subheader: "",
    season: 2,
    episode: 7,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "August 14 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: LargeTimerCard,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 6,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 6",
    releaseDateTime: "August 15 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 20%",
    TimerCard: LargeTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: Highest2LowestLogo.src,
    title: "Highest 2 Lowest",
    subheader: "",
    synopsis:
      "When a titan music mogul is targeted with a ransom plot, he is jammed up in a life-or-death moral dilemma.",
    cardMedia: Highest2Lowest.src,
    cardMediaAlt: "Highest 2 Lowest",
    releaseDateTime: "August 15 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.fandango.com/highest-2-lowest-2025-240338/movie-overview",
    objectPosition: "50% 80%",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
    isMovie: true,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 7,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 17 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: MasterchefLogo.src,
    title: "Masterchef",
    subheader: "Divide & Conquer",
    season: 15,
    episode: 13,
    cardMedia: Masterchef.src,
    cardMediaAlt: "Masterchef",
    releaseDateTime: "August 20 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.hulu.com/series/45d67197-5346-4adb-9d90-6ed2d7b7bd85",
    objectPosition: "100% 27%",
    TimerCard: LargeTimerCard,
    SiteLogo: HuluLogo,
    finale: true,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dandadan",
    subheader: "",
    season: 2,
    episode: 8,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "August 21 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "August 21 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: LargeTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 7,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 7",
    releaseDateTime: "August 22 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 1,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "August 22 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: LargeTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 8,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 24 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dandadan",
    subheader: "",
    season: 2,
    episode: 9,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "August 28 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 2,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "August 28 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 8,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 8",
    releaseDateTime: "August 29 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 2,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "August 29 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 9,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "August 31 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dandadan",
    subheader: "",
    season: 2,
    episode: 10,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "September 04 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 3,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 04 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 9,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 9",
    releaseDateTime: "September 05 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 3,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "September 05 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 10,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "September 07 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 1,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "September 09, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: LargeTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 2,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "September 09, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 3,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "September 09, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dandadan",
    subheader: "",
    season: 2,
    episode: 11,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "September 11 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 4,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 11 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: FoundationAvatar.src,
    title: "Foundation",
    subheader: "",
    season: 3,
    episode: 10,
    cardMedia: FoundationSeason3.src,
    cardMediaAlt: "Foundation Season 3 Episode 10",
    releaseDateTime: "September 12 2025 03:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/foundation/umc.cmc.5983fipzqbicvrve6jdfep4x3",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    finale: true,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 4,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "September 12 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 11,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "September 14 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 4,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "September 16, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: DandadanLogo.src,
    title: "Dandadan",
    subheader: "",
    season: 2,
    episode: 12,
    cardMedia: DanDaDan.src,
    cardMediaAlt: "Dandadan",
    releaseDateTime: "September 18 2025 09:00:00 GMT-0700",
    synopsis: ``,
    watchUrl: "https://www.crunchyroll.com/series/GG5H5XQ0D/dan-da-dan",
    objectPosition: "50% 40%",
    SiteLogo: CrunchyrollLogo,
    finale: true,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 5,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 18 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: LostBusLogo.src,
    title: "The Lost Bus",
    subheader: "",
    synopsis:
      "Explores what went wrong in California's Camp Fire, the nation's deadliest wildfire in a century, and how to prevent future tragedies, also including stories of a bus driver and school teacher who helped through a wildfire.",
    cardMedia: LostBus.src,
    cardMediaAlt: "The Lost Bus",
    releaseDateTime: "September 19 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.imdb.com/title/tt21103218/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520lost%2520bus",
    objectPosition: "50% 20%",
    TimerCard: LargeTimerCard,
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 5,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "September 19 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: NyaightLogo.src,
    title: "Nyaight of the Living Cat",
    subheader: "",
    season: 1,
    episode: 12,
    cardMedia: Nyaight.src,
    cardMediaAlt: "Nyaight of the Living Cat",
    releaseDateTime: "September 21 2025 07:15:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://www.crunchyroll.com/series/GKEH2G0DN/nyaight-of-the-living-cat",
    objectPosition: "50% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    finale: true,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 5,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "September 23, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 1,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "September 24, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: LargeTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 2,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "September 24, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 6,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "September 25 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 35%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: OneBattleLogo.src,
    title: "One Battle After Another",
    subheader: "",
    cardMedia: OneBattle.src,
    cardMediaAlt: "One Battle After Another",
    releaseDateTime: "September 26 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.fandango.com/one-battle-after-another-2025-241516/movie-overview",
    objectPosition: "50% 70%",
    synopsis:
      "When their evil enemy resurfaces after 16 years, a group of ex-revolutionaries reunite to rescue one of their own's daughter.",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 6,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "September 26 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 6,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "September 30, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 3,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 01, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 7,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "October 02 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 7,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "October 03 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 1,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "October 05, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 7,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "October 07, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 4,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 08, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: PeacemakerLogo.src,
    title: "Peacemaker",
    subheader: "",
    season: 2,
    episode: 8,
    cardMedia: PeacemakerSeason2.src,
    cardMediaAlt: "Peacemaker Season 2",
    releaseDateTime: "October 09 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://play.hbomax.com/show/a939d96b-7ffb-4481-96f6-472838d104ca",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: HBOLogo,
    finale: true,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 8,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "October 10 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 8,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "October 14, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 5,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 15, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 9,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "October 17 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 9,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "October 21, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
  },
  {
    avatar: SlowHorsesLogo.src,
    title: "Slow Horses",
    subheader: "",
    season: 5,
    episode: 6,
    cardMedia: SlowHorsesBig.src,
    cardMediaAlt: "Slow Horses",
    releaseDateTime: "October 22, 2025 21:00:00",
    watchUrl:
      "https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    addContrastToTimer: true,
    finale: true,
  },
  {
    avatar: NobodyWantsLogo.src,
    title: "Nobody Wants This",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: NobodyWants.src,
    cardMediaAlt: "Nobody Wants This",
    releaseDateTime: "October 23, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/81591296",
    objectPosition: "50% 50%",
    TimerCard: LargeTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "",
    season: 3,
    episode: 10,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    releaseDateTime: "October 24 2025 21:00:00 GMT-0700",
    watchUrl:
      "https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6",
    objectPosition: "35% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: AppleLogo,
    finale: true,
  },
  {
    avatar: OnlyMurdersLogo.src,
    title: "Only Murders In The Building",
    subheader: "",
    season: 5,
    episode: 10,
    cardMedia: OnlyMurdersintheBuilding.src,
    cardMediaAlt: "Only Murders In The Building",
    releaseDateTime: "October 28, 2025 21:00:00",
    watchUrl:
      "https://www.hulu.com/series/ef31c7e1-cd0f-4e07-848d-1cbfedb50ddf",
    objectPosition: "100% 20%",
    TimerCard: SmallTimerCard,
    SiteLogo: HuluLogo,
    finale: true,
  },
  {
    avatar: Pochita.src,
    title: "Chainsaw Man - The Movie: Reze Arc",
    subheader: "",
    cardMedia: ChainsawManMovie.src,
    cardMediaAlt: "Chainsaw Man - The Movie: Reze Arc",
    releaseDateTime: "October 29, 2025 16:00:00",
    synopsis:
      "Denji encounters a new romantic interest, Reze, who works at a coffee café.",
    isMovie: true,
    watchUrl:
      "https://www.fandango.com/chainsaw-man-the-movie-reze-arc-2025-241288/movie-overview",
    objectPosition: "50% 25%",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
    addContrastToTimer: true,
  },
  {
    avatar: RunningManLogo.src,
    title: "The Running Man",
    subheader: "",
    cardMedia: RunningMan.src,
    cardMediaAlt: "The Running Man",
    releaseDateTime: "November 07, 2025 16:00:00",
    synopsis: `A man joins a game show where contestants, allowed to go anywhere in the world, are pursued by "hunters" hired to kill them.`,
    isMovie: true,
    watchUrl:
      "https://www.fandango.com/the-running-man-2025-241290/movie-overview",
    objectPosition: "50% 25%",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter One: The Crawl",
    season: 5,
    episode: 1,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: LargeTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Two: The Vanishing of",
    season: 5,
    episode: 2,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Three: The Turnbow Trap",
    season: 5,
    episode: 3,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Four: Sorcerer",
    season: 5,
    episode: 4,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Five: Shock Jock",
    season: 5,
    episode: 5,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Six: Escape from Camazotz",
    season: 5,
    episode: 6,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Seven: The Bridge",
    season: 5,
    episode: 7,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Eight: The Rightside Up",
    season: 5,
    episode: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 31, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
    finale: true,
  },
  {
    avatar: FrierenLogo.src,
    title: "Frieren: Beyond Journey's End",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: FrierenFrierensParty.src,
    cardMediaAlt: "Frieren's Party",
    releaseDateTime: "January 31, 2026 23:00:00",
    watchUrl:
      "https://www.crunchyroll.com/series/GG5H5XQX4/frieren-beyond-journeys-end",
    estimate: true,
    estimateDate: "January 2026",
    objectPosition: "50% 28%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: OdysseyLogo.src,
    title: "The Odyssey",
    subheader: "",
    cardMedia: Odyssey.src,
    cardMediaAlt: "The Odyssey",
    releaseDateTime: "July 17, 2026 16:00:00",
    synopsis: `Follows Odysseus in his perilous journey home after the Trojan War, showcasing his encounters with Polyphemus, the Sirens, Circe, and finishing with his reunion with his wife, Penelope.`,
    isMovie: true,
    watchUrl: "https://www.fandango.com/the-odyssey-2026-241283/movie-overview",
    objectPosition: "50% 80%",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
    // addContrastToTimer: true,
  },
];
