import LargeTimerCard from "../components/largeTimerCard";
import SmallTimerCard from "../components/smallTimerCard";
import {
  AppleLogo,
  CrunchyrollLogo,
  FandangoLogo,
  GooglePlayMoviesLogo,
  HBOLogo,
  HuluLogo,
  IMDBLogo,
  NetflixLogo,
  YoutubeLogo,
} from "./svgs/svgLogos";

import TwentyEightYears from "./assets/28Years.jpg";
import TwentyEightYearsLogo from "./assets/28YearsLogo.jpg";
import ApothecaryDiaries from "./assets/ApothecaryDiaries.jpg";
import Attack from "./assets/Attack.jpg";
import AttackLogo from "./assets/AttackLogo.jpg";
import ChainsawManMovie from "./assets/ChainsawManMovie.jpg";
import Delicious from "./assets/Delicious.jpg";
import Dorohedoro from "./assets/Dorohedoro.jpg";
import DownCemetery from "./assets/DownCemetery.jpg";
import Evangelion from "./assets/Evangelion.jpg";
import Fantastic from "./assets/Fantastic.jpg";
import FantasticLogo from "./assets/FantasticLogo.jpg";
import FrierenFrierensParty from "./assets/FrierenFrierensParty.jpg";
import FrierenLogo from "./assets/FrierenLogo.jpg";
import Fruits from "./assets/Fruits.jpg";
import Haikyu from "./assets/Haikyu.jpg";
import HellsKitchen from "./assets/HellsKitchen.jpg";
import HellsKitchenLogo from "./assets/HellsKitchenLogo.jpg";
import Highest2Lowest from "./assets/Highest2Lowest.jpg";
import Highest2LowestLogo from "./assets/Highest2LowestLogo.jpg";
import Invasion from "./assets/Invasion.jpg";
import InvasionLogo from "./assets/InvasionLogo.jpg";
import JamesLogo from "./assets/JamesLogo.jpg";
import JeffBuckley from "./assets/JeffBuckley.jpg";
import JeffBuckleyLogo from "./assets/JeffBuckleyLogo.jpg";
import LostBus from "./assets/LostBus.jpg";
import LostBusLogo from "./assets/LostBusLogo.jpg";
import Mickey17 from "./assets/Mickey17.jpg";
import Mickey17Logo from "./assets/Mickey17Logo.jpg";
import MyHeroFinalSeason from "./assets/MyHeroFinalSeason.jpg";
import MyHeroLogo from "./assets/MyHeroLogo.jpg";
import Naruto from "./assets/Naruto.jpg";
import NobodyWants from "./assets/NobodyWants.jpg";
import NobodyWantsLogo from "./assets/NobodyWantsLogo.jpg";
import Odyssey from "./assets/Odyssey.jpg";
import OdysseyLogo from "./assets/OdysseyLogo.jpg";
import OneBattle from "./assets/OneBattle.jpg";
import OneBattleLogo from "./assets/OneBattleLogo.jpg";
import Pluribus from "./assets/Pluribus.jpg";
import ResidentAlien from "./assets/ResidentAlien.jpg";
import ResidentAlienLogo from "./assets/ResidentAlienLogo.jpg";
import RunningMan from "./assets/RunningMan.jpg";
import RunningManLogo from "./assets/RunningManLogo.jpg";
import Sandman from "./assets/Sandman.jpg";
import SandmanLogo from "./assets/SandmanLogo.jpg";
import SquidGame from "./assets/SquidGameCoffins.jpg";
import SquidLogo from "./assets/SquidLogo.jpg";
import Stone from "./assets/Stone.jpg";
import StoneLogo from "./assets/StoneLogo.jpg";
import StrangerLogo from "./assets/StrangerLogo.jpg";
import StrangerThings from "./assets/StrangerThings.jpg";
import Tar from "./assets/Tar.jpg";
import TarLogo from "./assets/TarLogo.jpg";
import Taskmaster from "./assets/Taskmaster.jpg";
import TaskmasterLogo from "./assets/TaskmasterLogo.jpg";
import TheBearLogo from "./assets/TheBearLogo.jpg";
import TheBearS4E6 from "./assets/TheBearS4E6.jpg";
import TheBrutalist from "./assets/TheBrutalist.jpg";
import TheBrutalistLogo from "./assets/TheBrutalistLogo.jpg";
import WhiteLotusLogo from "./assets/WhiteLotusLogo.jpg";
import WhiteLotusS2 from "./assets/WhiteLotusS2.jpg";
import WickedForGood from "./assets/WickedForGood.jpg";
import WickedForGoodLogo from "./assets/WickedForGoodLogo.jpg";
import ZoneOfInterest from "./assets/ZoneOfInterest.jpg";
import ZoneOfInterestLogo from "./assets/ZoneOfInterestLogo.jpg";

export interface AvailableNowProps {
  avatar: string;
  title: string;
  shortTitle?: string;
  subheader: string;
  season?: number;
  episode?: number;
  episodesInSeason?: number;
  cardMedia: string;
  cardMediaAlt: string;
  releaseDateTime: string;
  synopsis?: string;
  watchUrl: string;
  imdbUrl?: string;
  estimate?: boolean;
  estimateDate?: string;
  isMovie?: boolean;
  addContrastToTimer?: boolean;
  objectPosition?: string;
  finale?: boolean;
  SiteLogo:
    | typeof AppleLogo
    | typeof CrunchyrollLogo
    | typeof FandangoLogo
    | typeof HBOLogo
    | typeof HuluLogo
    | typeof NetflixLogo;
}

export interface UpNextProps extends AvailableNowProps {
  TimerCard: typeof LargeTimerCard | typeof SmallTimerCard;
}

export const availableNow: AvailableNowProps[] = [
  {
    avatar: HellsKitchen.src,
    title: "Hells Kitchen",
    subheader: "Hell on a Halfshell",
    season: 24,
    episode: 2,
    episodesInSeason: 11,
    cardMedia: HellsKitchen.src,
    cardMediaAlt: "Hells Kitchen",
    releaseDateTime: "October 02 2025 21:00:00 GMT-0700",
    synopsis: `The chefs are challenged with shucking and preparing the perfect scallop dish.`,
    watchUrl:
      "https://www.hulu.com/series/4f31f13a-d60c-4c90-b8e5-397ea49d08db?utm_source=shared_link",
    imdbUrl: "https://www.imdb.com/title/tt38525498/?ref_=ttep_ep_2",
    objectPosition: "50% 50%",
    SiteLogo: HuluLogo,
  },
  {
    avatar: Fruits.src,
    title: "Fruits Basket",
    subheader: "I Mean ... You Know, Right?",
    season: 3,
    episode: 5,
    episodesInSeason: 13,
    cardMedia: Fruits.src,
    cardMediaAlt: "Fruits Basket",
    releaseDateTime: "May 04 2021 03:00:00 GMT-0700",
    synopsis: `Momiji seems completely different this school year. He's got a taller body and a deeper voice, but has anything changed on the inside?`,
    watchUrl: "https://www.crunchyroll.com/series/G6ZJMGEXY/fruits-basket",
    imdbUrl: "https://www.imdb.com/title/tt14491220/?ref_=ttep_ep_5",
    objectPosition: "50% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: Dorohedoro.src,
    title: "Dorohedoro",
    subheader:
      "A Good Day to Leave / Mr. Monster, La-la-la / A Good Day to Leave 2 / Gorgeous and Gorging / Blue Night Land",
    season: 1,
    episode: 8,
    episodesInSeason: 12,
    cardMedia: Dorohedoro.src,
    cardMediaAlt: "Dorohedoro",
    releaseDateTime: "March 02, 2020 21:00:00",
    synopsis: `Fearing for Nikaido's safety, Caiman returns to the sorcerers' world alone. The En family begins preparations for the Blue Night Party festivities.`,
    watchUrl:
      "https://www.netflix.com/us/title/80991903?s=a&trkid=13747225&trg=cp&vlang=en&clip=81221930",
    imdbUrl: "https://www.imdb.com/title/tt11789992/?ref_=ttep_ep_8",
    objectPosition: "50% 50%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: AttackLogo.src,
    title: "Attack on Titan",
    subheader: "Above and Below",
    season: 4,
    episode: 16,
    episodesInSeason: 30,
    cardMedia: Attack.src,
    cardMediaAlt: "Attack on Titan",
    releaseDateTime: "May 02 2021 03:00:00 GMT-0700",
    synopsis: `With the Jaegerists now in charge, Zeke's master plan is revealed. But before it is put in motion, Eren recruits help to flush out any invaders in their midst.`,
    watchUrl: "https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan",
    imdbUrl: "https://www.imdb.com/title/tt14134634/?ref_=ttep_ep_16",
    objectPosition: "15% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: DownCemetery.src,
    title: "Down Cemetery Road",
    subheader: "",
    season: 1,
    episode: 1,
    episodesInSeason: 8,
    cardMedia: DownCemetery.src,
    cardMediaAlt: "Down Cemetery Road",
    releaseDateTime: "October 29 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
    imdbUrl: "https://www.imdb.com/title/tt33552603/?ref_=ttep_ep_1",
    objectPosition: "50% 30%",
    SiteLogo: AppleLogo,
  },
  {
    avatar: TheBearLogo.src,
    title: "The Bear",
    subheader: "Goodbye",
    season: 4,
    episode: 10,
    episodesInSeason: 10,
    cardMedia: TheBearLogo.src,
    cardMediaAlt: "The Bear Season 4",
    releaseDateTime: "June 25, 2025 21:00:00",
    synopsis: "Time waits for no one.",
    watchUrl:
      "https://www.hulu.com/series/05eb6a8e-90ed-4947-8c0b-e6536cbddd5f",
    imdbUrl: "https://www.imdb.com/title/tt36944202/?ref_=ttep_ep_10",
    objectPosition: "50% 50%",
    SiteLogo: HuluLogo,
  },
  {
    avatar: Evangelion.src,
    title: "Neon Genesis Evangelion",
    subheader: `She Said, 'Don't Make Others Suffer for Your Personal Hatred'`,
    season: 1,
    episode: 12,
    episodesInSeason: 26,
    cardMedia: Evangelion.src,
    cardMediaAlt: "Neon Genesis Evangelion",
    releaseDateTime: "December 20, 1995 21:00:00",
    synopsis: `Misato is promoted to the rank of Major, but she reveals her long-buried sentiments concerning her work at NERV. A massive Angel appears in Earth's stratosphere, and all three Evangelions are deployed to stop it.`,
    watchUrl:
      "https://www.netflix.com/us/title/81033445?s=a&trkid=13747225&trg=dsms&vlang=en&clip=81722672",
    imdbUrl: "https://www.imdb.com/title/tt0781966/?ref_=ttep_ep_12",
    objectPosition: "50% 30%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: Delicious.src,
    title: "Delicious in Dungeon",
    subheader: "Ice Golem/Barometz",
    season: 1,
    episode: 20,
    episodesInSeason: 24,
    cardMedia: Delicious.src,
    cardMediaAlt: "Delicious in Dungeon",
    releaseDateTime: "May 16 2024 03:00:00 GMT-0700",
    synopsis: `Izutsumi proves to be a useful ally despite her lousy table manners - and aversion to eating monsters. But the crew's kindness slowly opens her up.`,
    watchUrl:
      "https://www.netflix.com/us/title/81564899?s=a&trkid=13747225&trg=cp&vlang=en&clip=81751898",
    imdbUrl: "https://www.imdb.com/title/tt32328115/?ref_=ttep_ep_20",
    objectPosition: "50% 50%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: Haikyu.src,
    title: "Haikyu!!",
    subheader: `Townsperson B`,
    season: 2,
    episode: 3,
    episodesInSeason: 25,
    cardMedia: Haikyu.src,
    cardMediaAlt: "Haikyu!!",
    releaseDateTime: "October 18, 2015 21:00:00",
    synopsis: `Yachi has mixed feelings about joining the team, and she is less than thrilled to ask her mother for advice for fear that she might disapprove. That's when Hinata steps in to help her overcome her fears.`,
    watchUrl: "https://www.crunchyroll.com/series/GY8VM8MWY/haikyu",
    imdbUrl: "https://www.imdb.com/title/tt6009010/?ref_=ttep_ep_3",
    objectPosition: "50% 30%",
    SiteLogo: CrunchyrollLogo,
  },
];

export const backlog: AvailableNowProps[] = [
  {
    avatar: NobodyWantsLogo.src,
    title: "Nobody Wants This",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: NobodyWants.src,
    cardMediaAlt: "Nobody Wants This",
    releaseDateTime: "October 23, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/81591296",
    objectPosition: "50% 50%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: OneBattleLogo.src,
    title: "One Battle After Another",
    subheader: "",
    cardMedia: OneBattle.src,
    cardMediaAlt: "One Battle After Another",
    releaseDateTime: "September 26 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.fandango.com/one-battle-after-another-2025-241516/movie-overview",
    objectPosition: "50% 70%",
    synopsis:
      "When their evil enemy resurfaces after 16 years, a group of ex-revolutionaries reunite to rescue one of their own's daughter.",
    SiteLogo: FandangoLogo,
  },
  {
    avatar: TaskmasterLogo.src,
    title: "Taskmaster",
    subheader: "9x7",
    season: 20,
    episode: 1,
    episodesInSeason: 10,
    cardMedia: Taskmaster.src,
    cardMediaAlt: "Taskmaster",
    releaseDateTime: "September 11 2025 21:00:00 GMT-0700",
    synopsis:
      "Greg Davies and Alex Horne host five comedians - Maisie Adam, Reece Shearsmith, Sanjeev Bhaskar, Phil Ellis and Ania Magliano - in tasks involving codes, gym balls and gross sounds, testing skills and dignity.",
    watchUrl:
      "https://youtube.com/playlist?list=PLRWvNQVqAeWKj3-psfj3jrsqtCnPoE178&si=nWt5PTpRSe1uc76I",
    imdbUrl: "https://www.imdb.com/title/tt37520605/?ref_=ttep_ep_1",
    objectPosition: "50% 50%",
    SiteLogo: YoutubeLogo,
  },
  {
    avatar: StoneLogo.src,
    title: "Dr. Stone",
    subheader: "New World Map",
    season: 3,
    episode: 1,
    episodesInSeason: 22,
    cardMedia: Stone.src,
    cardMediaAlt: "Dr. Stone",
    releaseDateTime: "June 04 2023 03:00:00 GMT-0700",
    synopsis: `While continuing to use the hot air balloon to search for the oil, it's decided that Ishigami Village needs to take up agriculture to prevent future food shortages, as well as to produce preserved food for their upcoming sea voyage.`,
    watchUrl: "https://www.crunchyroll.com/series/GYEXQKJG6/dr-stone",
    imdbUrl: "https://www.imdb.com/title/tt21479732/?ref_=ttep_ep_1",
    objectPosition: "50% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: InvasionLogo.src,
    title: "Invasion",
    subheader: "The Ones We Leave Behind",
    season: 3,
    episode: 1,
    episodesInSeason: 10,
    cardMedia: Invasion.src,
    cardMediaAlt: "Invasion",
    synopsis:
      "Trevante returns to an Earth that’s different than the one he left two years ago. Jamila struggles to adapt to this new world.",
    releaseDateTime: "August 22 2025 03:00:00 GMT-0700",
    watchUrl: `https://tv.apple.com/us/show/invasion/umc.cmc.70b7z97fv7azfzn5baqnj88p6`,
    imdbUrl: "https://www.imdb.com/title/tt30825175/?ref_=tt_ov_ep_pr",
    objectPosition: "35% 30%",
    SiteLogo: AppleLogo,
  },
  {
    avatar: LostBusLogo.src,
    title: "The Lost Bus",
    subheader: "",
    synopsis:
      "Explores what went wrong in California's Camp Fire, the nation's deadliest wildfire in a century, and how to prevent future tragedies, also including stories of a bus driver and school teacher who helped through a wildfire.",
    cardMedia: LostBus.src,
    cardMediaAlt: "The Lost Bus",
    releaseDateTime: "September 19 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.imdb.com/title/tt21103218/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520lost%2520bus",
    objectPosition: "50% 20%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: Highest2LowestLogo.src,
    title: "Highest 2 Lowest",
    subheader: "",
    synopsis:
      "When a titan music mogul is targeted with a ransom plot, he is jammed up in a life-or-death moral dilemma.",
    cardMedia: Highest2Lowest.src,
    cardMediaAlt: "Highest 2 Lowest",
    releaseDateTime: "August 15 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.fandango.com/highest-2-lowest-2025-240338/movie-overview",
    imdbUrl:
      "https://www.imdb.com/title/tt31194612/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_highest",
    objectPosition: "50% 80%",
    SiteLogo: FandangoLogo,
    isMovie: true,
  },
  {
    avatar: JeffBuckleyLogo.src,
    title: "It's Never Over, Jeff Buckley",
    subheader: "",
    synopsis:
      "Never-before-seen footage, exclusive voice messages, and accounts from Jeff Buckley's inner circle paint a captivating portrait of the gifted musician who died tragically in 1997, having only released one album.",
    cardMedia: JeffBuckley.src,
    cardMediaAlt: "It's Never Over, Jeff Buckley",
    releaseDateTime: "August 08 2025 16:00:00 GMT-0700",
    watchUrl:
      "https://www.fandango.com/its-never-over-jeff-buckley-2025-241047/movie-overview",
    imdbUrl:
      "https://www.imdb.com/title/tt34966650/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_jeff%2520buck",
    objectPosition: "65% 40%",
    SiteLogo: FandangoLogo,
    isMovie: true,
  },
  {
    avatar: FantasticLogo.src,
    title: "The Fantastic Four: First Steps",
    subheader: "",
    cardMedia: Fantastic.src,
    cardMediaAlt: "The Fantastic Four: First Steps",
    releaseDateTime: "July 25 2025 16:00:00 GMT-0700",
    synopsis:
      "Forced to balance their roles as heroes with the strength of their family bond, the Fantastic Four must defend Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    watchUrl:
      "https://www.fandango.com/the-fantastic-four-first-steps-2025-236967/movie-overview",
    imdbUrl:
      "https://www.imdb.com/title/tt10676052/?ref_=nv_sr_srsg_2_tt_6_nm_0_in_0_q_fantasti",
    objectPosition: "47% 15%",
    SiteLogo: FandangoLogo,
  },
  {
    avatar: ResidentAlienLogo.src,
    title: "Resident Alien",
    subheader: "Prisoners",
    season: 4,
    episode: 1,
    episodesInSeason: 10,
    cardMedia: ResidentAlien.src,
    cardMediaAlt: "Resident Alien",
    releaseDateTime: "June 06 2025 16:00:00 GMT-0700",
    synopsis:
      "Harry must escape an outer space prison to stop a dangerous threat in town.",
    watchUrl: "https://www.imdb.com/title/tt8690918/?ref_=ttep_ov_bk",
    imdbUrl: "https://www.imdb.com/title/tt32641415/?ref_=ttep_ep_1",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
  },
  {
    avatar: SquidLogo.src,
    title: "Squid Game",
    subheader: "Keys and Knives",
    season: 3,
    episode: 1,
    episodesInSeason: 6,
    cardMedia: SquidGame.src,
    cardMediaAlt: "Squid Game",
    releaseDateTime: "July 27 2025 16:00:00 GMT-0700",
    synopsis:
      "No-eul infiltrates a dangerous operation with a risky plan. A new game is announced: hide-and-seek, where one group holds a key and the other a knife.",
    watchUrl: "https://www.netflix.com/us/title/81040344",
    imdbUrl: "https://www.imdb.com/title/tt33056155/?ref_=ttep_ep_1",
    objectPosition: "50% 50%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: SandmanLogo.src,
    title: "The Sandman",
    subheader: "Season of Mists",
    season: 2,
    episode: 1,
    episodesInSeason: 12,
    cardMedia: Sandman.src,
    cardMediaAlt: "The Sandman",
    releaseDateTime: "July 03 2025 16:00:00 GMT-0700",
    synopsis:
      "When a gathering of the Endless exposes deep-seated grievances, Morpheus embarks on a mission to Hell to free the soul of a condemned mortal.",
    watchUrl: "https://www.netflix.com/us/title/81150303",
    imdbUrl: "https://www.imdb.com/title/tt23218892/?ref_=ttep_ep_1",
    objectPosition: "50% 50%",
    SiteLogo: NetflixLogo,
  },
  {
    avatar: Naruto.src,
    title: "Naruto",
    subheader: "Identify Yourself: Powerful New Rivals",
    season: 1,
    episode: 21,
    episodesInSeason: 50,
    cardMedia: Naruto.src,
    cardMediaAlt: "Naruto",
    releaseDateTime: "February 27 2003 16:00:00 GMT-0700",
    synopsis:
      "After the three ninjas take their leave, Sasuke realizes he has a powerful rival out there. The next day, Kakashi announces that he has recommended all of them for the Chuunin Exams. While Naruto and Sasuke are pleased, Sakura is afraid of letting everyone down. Also, someone decides they aren't ready and decides to test their abilities.",
    watchUrl: "https://www.crunchyroll.com/series/GY9PJ5KWR/naruto",
    imdbUrl: "https://www.imdb.com/title/tt0878183/?ref_=ttep_ep_21",
    objectPosition: "50% 50%",
    SiteLogo: CrunchyrollLogo,
  },
  {
    avatar: WhiteLotusLogo.src,
    title: "White Lotus",
    subheader: "Ciao",
    season: 2,
    episode: 1,
    episodesInSeason: 7,
    cardMedia: WhiteLotusS2.src,
    cardMediaAlt: "White Lotus",
    releaseDateTime: "October 30 2022 16:00:00 GMT-0700",
    synopsis:
      "Two couples navigate awkwardness, an Italian American family deals with a conspicuous absence, and Tanya arrives with her new assistant.",
    watchUrl:
      "https://play.hbomax.com/show/14f9834d-bc23-41a8-ab61-5c8abdbea505",
    imdbUrl: "https://www.imdb.com/title/tt15208848/?ref_=ttep_ep_1",
    objectPosition: "50% 50%",
    SiteLogo: HBOLogo,
  },
  {
    avatar: ZoneOfInterestLogo.src,
    title: "The Zone of Interest",
    subheader: "",
    cardMedia: ZoneOfInterest.src,
    cardMediaAlt: "The Zone of Interest",
    releaseDateTime: "December 15 2023 16:00:00 GMT-0700",
    synopsis:
      "Auschwitz commandant Rudolf Höss and his wife Hedwig strive to build a dream life for their family in a house and garden beside the camp.",
    watchUrl: "https://www.imdb.com/title/tt7160372/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: TheBrutalistLogo.src,
    title: "The Brutalist",
    subheader: "",
    cardMedia: TheBrutalist.src,
    cardMediaAlt: "The Brutalist",
    releaseDateTime: "January 2024 16:00:00 GMT-0700",
    synopsis:
      "A visionary architect flees post-war Europe in 1947 for a brighter future in the United States and finds his life forever changed by a wealthy client.",
    watchUrl: "https://www.imdb.com/title/tt8999762/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: TarLogo.src,
    title: "Tár",
    subheader: "",
    cardMedia: Tar.src,
    cardMediaAlt: "Tár",
    releaseDateTime: "October 07 2022 16:00:00 GMT-0700",
    synopsis:
      "Set in the international world of Western classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors and the very first female director of a major German orchestra.",
    watchUrl: "https://www.imdb.com/title/tt14444726/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: TwentyEightYearsLogo.src,
    title: "28 Years Later",
    subheader: "",
    cardMedia: TwentyEightYears.src,
    cardMediaAlt: "28 Years Later",
    releaseDateTime: "June 20 2025 16:00:00 GMT-0700",
    synopsis:
      "A group of survivors of the rage virus live on a small island. When one of the group leaves the island on a mission into the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors.",
    watchUrl: "https://www.imdb.com/title/tt10548174/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
  {
    avatar: Mickey17Logo.src,
    title: "Mickey 17",
    subheader: "",
    cardMedia: Mickey17.src,
    cardMediaAlt: "Mickey 17",
    releaseDateTime: "March 07 2025 16:00:00 GMT-0700",
    synopsis: `During a human expedition to colonize space, Mickey 17, a so-called "expendable" employee, is sent to explore an ice planet.`,
    watchUrl: "https://www.imdb.com/title/tt12299608/",
    objectPosition: "50% 50%",
    SiteLogo: IMDBLogo,
    isMovie: true,
  },
];

export const upNext: UpNextProps[] = [
  // {
  //   avatar: DownCemetery.src,
  //   title: "Down Cemetery Road",
  //   subheader: "",
  //   season: 1,
  //   episode: 2,
  //   episodesInSeason: 8,
  //   cardMedia: DownCemetery.src,
  //   cardMediaAlt: "Down Cemetery Road",
  //   releaseDateTime: "October 29 2025 21:00:00 GMT-0700",
  //   synopsis: "",
  //   watchUrl:
  //     "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
  //   imdbUrl: "https://www.imdb.com/title/tt33552604/?ref_=ttep_ep_2",
  //   objectPosition: "50% 30%",
  //   SiteLogo: AppleLogo,
  //   TimerCard: SmallTimerCard,
  // },
  // {
  //   avatar: HellsKitchenLogo.src,
  //   title: "Hells Kitchen",
  //   subheader: "",
  //   season: 24,
  //   episode: 6,
  //   episodesInSeason: 6,
  //   cardMedia: HellsKitchen.src,
  //   cardMediaAlt: "Hells Kitchen",
  //   releaseDateTime: "October 30 2025 21:00:00 GMT-0700",
  //   synopsis: ``,
  //   watchUrl:
  //     "https://www.hulu.com/series/4f31f13a-d60c-4c90-b8e5-397ea49d08db?utm_source=shared_link",
  //   imdbUrl: "https://www.imdb.com/title/tt38525505/?ref_=ttep_ep_6",
  //   objectPosition: "50% 50%",
  //   SiteLogo: HuluLogo,
  //   TimerCard: SmallTimerCard,
  // },
  // {
  //   avatar: TaskmasterLogo.src,
  //   title: "Taskmaster",
  //   subheader: "",
  //   season: 20,
  //   episode: 8,
  //   episodesInSeason: 10,
  //   cardMedia: Taskmaster.src,
  //   cardMediaAlt: "Taskmaster",
  //   releaseDateTime: "October 30 2025 21:00:00 GMT-0700",
  //   synopsis: "",
  //   watchUrl:
  //     "https://youtube.com/playlist?list=PLRWvNQVqAeWKj3-psfj3jrsqtCnPoE178&si=nWt5PTpRSe1uc76I",
  //   imdbUrl: "https://www.imdb.com/title/tt37520619/?ref_=ttep_ep_8",
  //   objectPosition: "50% 30%",
  //   SiteLogo: YoutubeLogo,
  //   TimerCard: SmallTimerCard,
  // },
  // {
  //   avatar: DownCemetery.src,
  //   title: "Down Cemetery Road",
  //   subheader: "",
  //   season: 1,
  //   episode: 3,
  //   episodesInSeason: 8,
  //   cardMedia: DownCemetery.src,
  //   cardMediaAlt: "Down Cemetery Road",
  //   releaseDateTime: "Novermber 05 2025 21:00:00 GMT-0700",
  //   synopsis: "",
  //   watchUrl:
  //     "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
  //   imdbUrl: "https://www.imdb.com/title/tt33552605/?ref_=ttep_ep_3",
  //   objectPosition: "50% 30%",
  //   SiteLogo: AppleLogo,
  //   TimerCard: SmallTimerCard,
  // },
  // {
  //   avatar: TaskmasterLogo.src,
  //   title: "Taskmaster",
  //   subheader: "",
  //   season: 20,
  //   episode: 9,
  //   episodesInSeason: 10,
  //   cardMedia: Taskmaster.src,
  //   cardMediaAlt: "Taskmaster",
  //   releaseDateTime: "November 06 2025 21:00:00 GMT-0700",
  //   synopsis: "",
  //   watchUrl:
  //     "https://youtube.com/playlist?list=PLRWvNQVqAeWKj3-psfj3jrsqtCnPoE178&si=nWt5PTpRSe1uc76I",
  //   imdbUrl: "https://www.imdb.com/title/tt37520623/?ref_=ttep_ep_9",
  //   objectPosition: "50% 30%",
  //   SiteLogo: YoutubeLogo,
  //   TimerCard: SmallTimerCard,
  // },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 1,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "November 07 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt30759782/?ref_=ttep_ep_1",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: LargeTimerCard,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 2,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "November 07 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32767308/?ref_=ttep_ep_2",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: RunningManLogo.src,
    title: "The Running Man",
    subheader: "",
    cardMedia: RunningMan.src,
    cardMediaAlt: "The Running Man",
    releaseDateTime: "November 07, 2025 16:00:00",
    synopsis: `A man joins a game show where contestants, allowed to go anywhere in the world, are pursued by "hunters" hired to kill them.`,
    isMovie: true,
    watchUrl:
      "https://www.fandango.com/the-running-man-2025-241290/movie-overview",
    objectPosition: "50% 25%",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 4,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "November 09, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: DownCemetery.src,
    title: "Down Cemetery Road",
    subheader: "",
    season: 1,
    episode: 4,
    episodesInSeason: 8,
    cardMedia: DownCemetery.src,
    cardMediaAlt: "Down Cemetery Road",
    releaseDateTime: "Novermber 12 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
    imdbUrl: "https://www.imdb.com/title/tt33552606/?ref_=ttep_ep_4",
    objectPosition: "50% 30%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: TaskmasterLogo.src,
    title: "Taskmaster",
    subheader: "",
    season: 20,
    episode: 10,
    episodesInSeason: 10,
    cardMedia: Taskmaster.src,
    cardMediaAlt: "Taskmaster",
    releaseDateTime: "November 13 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://youtube.com/playlist?list=PLRWvNQVqAeWKj3-psfj3jrsqtCnPoE178&si=nWt5PTpRSe1uc76I",
    imdbUrl: "https://www.imdb.com/title/tt37520630/?ref_=ttep_ep_10",
    objectPosition: "50% 30%",
    SiteLogo: YoutubeLogo,
    TimerCard: LargeTimerCard,
    finale: true,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 3,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "November 14 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32767323/?ref_=ttep_ep_3",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 5,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "November 16, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: DownCemetery.src,
    title: "Down Cemetery Road",
    subheader: "",
    season: 1,
    episode: 5,
    episodesInSeason: 8,
    cardMedia: DownCemetery.src,
    cardMediaAlt: "Down Cemetery Road",
    releaseDateTime: "Novermber 19 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
    imdbUrl: "https://www.imdb.com/title/tt33552607/?ref_=ttep_ep_5",
    objectPosition: "50% 30%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: WickedForGoodLogo.src,
    title: "Wicked: for Good",
    subheader: "",
    cardMedia: WickedForGood.src,
    cardMediaAlt: "Wicked: for Good",
    releaseDateTime: "November 21 2025 21:00:00 GMT-0700",
    synopsis:
      "Elphaba, the future Wicked Witch of the West and her relationship with Glinda, the Good Witch of the North. The second of a two-part feature film adaptation of the Broadway musical.",
    watchUrl:
      "https://www.fandango.com/wicked-for-good-2025-238985/movie-overview",
    imdbUrl: "https://www.imdb.com/title/tt19847976/?ref_=ttmi_ov_bk",
    objectPosition: "50% 30%",
    SiteLogo: FandangoLogo,
    TimerCard: LargeTimerCard,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 4,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "November 21 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32767327/?ref_=ttep_ep_4",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 6,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "November 23, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter One: The Crawl",
    season: 5,
    episode: 1,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: LargeTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Two: The Vanishing of",
    season: 5,
    episode: 2,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Three: The Turnbow Trap",
    season: 5,
    episode: 3,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Four: Sorcerer",
    season: 5,
    episode: 4,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "November 26, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: DownCemetery.src,
    title: "Down Cemetery Road",
    subheader: "",
    season: 1,
    episode: 6,
    episodesInSeason: 8,
    cardMedia: DownCemetery.src,
    cardMediaAlt: "Down Cemetery Road",
    releaseDateTime: "Novermber 26 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
    imdbUrl: "https://www.imdb.com/title/tt33552608/?ref_=ttep_ep_6",
    objectPosition: "50% 30%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 5,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "November 28 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32777418/?ref_=ttep_ep_5",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 7,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "November 30, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: DownCemetery.src,
    title: "Down Cemetery Road",
    subheader: "",
    season: 1,
    episode: 7,
    episodesInSeason: 8,
    cardMedia: DownCemetery.src,
    cardMediaAlt: "Down Cemetery Road",
    releaseDateTime: "December 03 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
    imdbUrl: "https://www.imdb.com/title/tt33552609/?ref_=ttep_ep_7",
    objectPosition: "50% 30%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 6,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "December 05 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32777420/?ref_=ttep_ep_6",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 8,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "December 07, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: DownCemetery.src,
    title: "Down Cemetery Road",
    subheader: "",
    season: 1,
    episode: 8,
    episodesInSeason: 8,
    cardMedia: DownCemetery.src,
    cardMediaAlt: "Down Cemetery Road",
    releaseDateTime: "December 10 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/down-cemetery-road/umc.cmc.3i55uxosnfpzw7rw1q525iksh",
    imdbUrl: "https://www.imdb.com/title/tt33552610/?ref_=ttep_ep_8",
    objectPosition: "50% 30%",
    SiteLogo: AppleLogo,
    TimerCard: LargeTimerCard,
    finale: true,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 7,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "December 12 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32777421/?ref_=ttep_ep_7",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 7,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "December 12 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32777421/?ref_=ttep_ep_7",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 9,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "December 14, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 8,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "December 19 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32777424/?ref_=ttep_ep_8",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 10,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "December 21, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: SmallTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Five: Shock Jock",
    season: 5,
    episode: 5,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Six: Escape from Camazotz",
    season: 5,
    episode: 6,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Seven: The Bridge",
    season: 5,
    episode: 7,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 25, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: SmallTimerCard,
    SiteLogo: NetflixLogo,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 9,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "December 26 2025 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32777427/?ref_=ttep_ep_9",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: SmallTimerCard,
  },
  {
    avatar: MyHeroLogo.src,
    title: "My Hero Academia",
    subheader: "",
    season: 8,
    episode: 11,
    episodesInSeason: 11,
    cardMedia: MyHeroFinalSeason.src,
    cardMediaAlt: "My Hero Academia Season 8",
    releaseDateTime: "December 28, 2025 01:30:00",
    watchUrl: "https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia",
    objectPosition: "50% 50%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
    finale: true,
  },
  {
    avatar: StrangerLogo.src,
    title: "Stranger Things",
    subheader: "Chapter Eight: The Rightside Up",
    season: 5,
    episode: 8,
    episodesInSeason: 8,
    cardMedia: StrangerThings.src,
    cardMediaAlt: "Stranger Things Season 5",
    releaseDateTime: "December 31, 2025 21:00:00",
    watchUrl: "https://www.netflix.com/us/title/80057281",
    objectPosition: "50% 30%",
    TimerCard: LargeTimerCard,
    SiteLogo: NetflixLogo,
    finale: true,
  },
  {
    avatar: Pluribus.src,
    title: "Pluribus",
    subheader: "",
    season: 1,
    episode: 10,
    episodesInSeason: 10,
    cardMedia: Pluribus.src,
    cardMediaAlt: "Pluribus",
    releaseDateTime: "January 02 2026 21:00:00 GMT-0700",
    synopsis: "",
    watchUrl:
      "https://tv.apple.com/us/show/pluribus/umc.cmc.37axgovs2yozlyh3c2cmwzlza",
    imdbUrl: "https://www.imdb.com/title/tt32767335/?ref_=ttep_ep_10",
    objectPosition: "50% 40%",
    SiteLogo: AppleLogo,
    TimerCard: LargeTimerCard,
    finale: true,
  },
  {
    avatar: FrierenLogo.src,
    title: "Frieren: Beyond Journey's End",
    subheader: "",
    season: 2,
    episode: 1,
    cardMedia: FrierenFrierensParty.src,
    cardMediaAlt: "Frieren's Party",
    releaseDateTime: "January 16, 2026 23:00:00",
    watchUrl:
      "https://www.crunchyroll.com/series/GG5H5XQX4/frieren-beyond-journeys-end",
    objectPosition: "50% 28%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
  {
    avatar: OdysseyLogo.src,
    title: "The Odyssey",
    subheader: "",
    cardMedia: Odyssey.src,
    cardMediaAlt: "The Odyssey",
    releaseDateTime: "July 17, 2026 16:00:00",
    synopsis: `Follows Odysseus in his perilous journey home after the Trojan War, showcasing his encounters with Polyphemus, the Sirens, Circe, and finishing with his reunion with his wife, Penelope.`,
    isMovie: true,
    watchUrl: "https://www.fandango.com/the-odyssey-2026-241283/movie-overview",
    objectPosition: "50% 80%",
    TimerCard: LargeTimerCard,
    SiteLogo: FandangoLogo,
    // addContrastToTimer: true,
  },
  {
    avatar: ApothecaryDiaries.src,
    title: "Apothecary Diaries",
    subheader: "",
    season: 3,
    episode: 1,
    cardMedia: ApothecaryDiaries.src,
    cardMediaAlt: "Apothecary Diaries",
    releaseDateTime: "October 31, 2026 23:00:00",
    watchUrl:
      "https://www.crunchyroll.com/series/G3KHEVDJ7/the-apothecary-diaries",
    estimateDate: "October 2026",
    objectPosition: "50% 28%",
    TimerCard: LargeTimerCard,
    SiteLogo: CrunchyrollLogo,
    addContrastToTimer: true,
  },
];
